apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backerei-payout-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backerei-payout-sender
spec:
  # every 3 hours
  schedule: "7 */3 * * *"
  concurrencyPolicy:  Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: backerei-payout-sender
        spec:
          securityContext:
            fsGroup: 100
          initContainers:
          - name: payout-cron
            image: payout-cron
            volumeMounts:
            - name: backerei-payout-storage
              mountPath: /var/run/backerei/payouts
            - name: backerei-config-storage
              mountPath: /var/run/backerei/config
            envFrom:
            - configMapRef:
                name: backerei-payout-configmap
            resources:
              limits:
                cpu: 0
          containers:
          - name: website-builder
            image: website-builder
            volumeMounts:
            - name: backerei-payout-storage
              mountPath: /var/run/backerei/payouts
              readOnly: true
            envFrom:
            - configMapRef:
                name: website-builder-configmap
            resources:
              limits:
                cpu: 0
          volumes:
          - name: backerei-config-storage
            emptyDir: {}
          - name: backerei-payout-storage
            persistentVolumeClaim:
              claimName: backerei-payout-storage-claim
          restartPolicy: OnFailure
