apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backerei-payout-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backerei-payout-sender
spec:
  # every 3 hours
  schedule: "7 */3 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: backerei-payout-sender
        spec:
          securityContext:
            fsGroup: 100
          initContainers:
          - name: payout-cron
            image: payout-cron
            volumeMounts:
            - name: backerei-payout-storage
              mountPath: /var/run/backerei/payouts
            - name: tezos-payout-client-storage
              mountPath: /var/run/tezos/client
            env:
            - name: PROTOCOL_SHORT
              valueFrom:
                configMapKeyRef:
                  name: tezos-configmap
                  key: PROTOCOL_SHORT
            - name: HOT_WALLET_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: hot-wallet
                  key: hot_wallet_private_key
            - name: HOT_WALLET_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: backerei-payout-configmap
                  key: HOT_WALLET_PUBLIC_KEY
            - name: CYCLE_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: backerei-payout-configmap
                  key: CYCLE_LENGTH
            - name: PRESERVED_CYCLES
              valueFrom:
                configMapKeyRef:
                  name: backerei-payout-configmap
                  key: PRESERVED_CYCLES
            - name: PAYOUT_DELAY
              valueFrom:
                configMapKeyRef:
                  name: backerei-payout-configmap
                  key: PAYOUT_DELAY
            - name: SNAPSHOT_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: backerei-payout-configmap
                  key: SNAPSHOT_INTERVAL
            - name: PUBLIC_BAKING_KEY
              valueFrom:
                configMapKeyRef:
                  name: tezos-configmap
                  key: PUBLIC_BAKING_KEY
            - name: PAYOUT_FEE
              valueFrom:
                configMapKeyRef:
                  name: backerei-payout-configmap
                  key: PAYOUT_FEE
            - name: PAYOUT_STARTING_CYCLE
              valueFrom:
                configMapKeyRef:
                  name: backerei-payout-configmap
                  key: PAYOUT_STARTING_CYCLE
            - name: WITNESS_PAYOUT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: backerei-payout-configmap
                  key: WITNESS_PAYOUT_ADDRESS
            resources:
              limits:
                cpu: 0
          containers:
          - name: website-builder
            image: website-builder
            volumeMounts:
            - name: backerei-payout-storage
              mountPath: /var/run/backerei/payouts
              readOnly: true
            - name: website-builder-credentials
              mountPath: /var/secrets/google
            envFrom:
            - configMapRef:
                name: website-builder-configmap
            resources:
              limits:
                cpu: 0
          volumes:
          - name: tezos-payout-client-storage
            emptyDir: {}
          - name: backerei-payout-storage
            persistentVolumeClaim:
              claimName: backerei-payout-storage-claim
          - name: website-builder-credentials
            secret:
              secretName: website-builder-credentials
          restartPolicy: OnFailure
