kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-public-node-rpc
spec:
  ports:
  - port: 8732
  selector:
    app: tezos-public-node
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tezos-public-node
spec:
  selector:
    matchLabels:
      app: tezos-public-node # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "tezos-public-node"
  replicas: 1
  template:
    metadata:
      labels:
        app: tezos-public-node # Pod template's label selector
    spec:
      securityContext:
        fsGroup: 100
      containers:
      - name: tezos-public-node
        image: tezos-node-with-probes
        args: [ "tezos-node", "--history-mode", "archive" ]
        ports:
        - containerPort: 8732
          name: tezos-rpc-port
        volumeMounts:
        - name: tezos-public-node-pv-claim
          mountPath: /var/run/tezos/node
        resources:
          limits:
            cpu: 0
        livenessProbe:
          # pod is considered dead when number of connections drops to zero
          exec:
            command:
            - /usr/local/bin/does-tezos-node-have-connections.sh
          periodSeconds: 10
          failureThreshold: 50
        #startupProbe:
        # TODO upgrade to k8s 1.16 because it does not work on 1.15
        # pod is not considered ready before it has at least one connection
        #exec:
        #command:
        #- /usr/local/bin/does-tezos-node-have-connections.sh
        #periodSeconds: 10
        #failureThreshold: 100
      - name: tezos-network-monitor
        image: tezos-network-monitor
        resources:
          limits:
            cpu: 0
        envFrom:
        - configMapRef:
            name: tezos-network-monitor-configmap
      initContainers:
      - name: tezos-archive-downloader
        image: tezos-archive-downloader
        args:
        - "$(ARCHIVE_URL)"
        env:
        - name: ARCHIVE_URL
          valueFrom:
            configMapKeyRef:
              name: tezos-configmap
              key: ARCHIVE_URL
        volumeMounts:
        - name: tezos-public-node-pv-claim
          mountPath: /var/run/tezos/node
        resources:
          limits:
            cpu: 0
  volumeClaimTemplates:
  - metadata:
      name: tezos-public-node-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-ssd
      resources:
        requests:
          storage: 60Gi
