apiVersion: v1
kind: Service
metadata:
  name: tezos-public-node
spec:
  ports:
  - port: 8732
  selector:
    app: tezos-public-node
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tezos-public-node
spec:
  selector:
    matchLabels:
      app: tezos-public-node # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "tezos-public-node"
  replicas: 1
  template:
    metadata:
      labels:
        app: tezos-public-node # Pod template's label selector
    spec:
      securityContext:
        fsGroup: 100
      containers:
      - name: tezos-public-node
        image: tezos-node-with-probes
        args: [ "tezos-node", "--history-mode", "archive", "--network", "$(TEZOS_NETWORK)" ]
          #command: [ "/bin/sleep", "10000000000" ]
        ports:
        - containerPort: 8732
          name: tezos-rpc-port
        volumeMounts:
        - name: tezos-public-node-pv-claim
          mountPath: /var/run/tezos/node
        env:
        - name: TEZOS_NETWORK
          valueFrom:
            configMapKeyRef:
              name: tezos-configmap
              key: TEZOS_NETWORK
        resources:
          limits:
            cpu: 0
        volumeMounts:
        - name: tezos-public-node-pv-claim
          mountPath: /var/run/tezos/node
        resources:
          limits:
            cpu: 0
  volumeClaimTemplates:
  - metadata:
      name: tezos-public-node-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-ssd
      resources:
        requests:
          storage: 90Gi
